version: '3.3'
services:
  psql:
    container_name: dev-portfolio-db
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 6432:5432
    volumes:
      - ./data/psql:/var/lib/postgresql/data
    networks:
      - portfolio
    env_file:
      - .env

  backend:
    container_name: dev-portfolio-back
    restart: on-failure
    build:
      context: .
      dockerfile: dockerfiles/development/backend.dockerfile
    ports:
      - 80:80
      - 9229:9229
    volumes:
      - ./backend:/usr/backend
      - /usr/backend/node_modules
    networks:
      - portfolio
    env_file:
      - ./backend/.env
    depends_on:
      - psql

  frontend:
    container_name: dev-portfolio-front
    restart: on-failure
    build:
      context: .
      dockerfile: dockerfiles/development/frontend.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/frontend
    networks:
      - portfolio
    env_file:
      - ./frontend/.env
    depends_on:
      - psql

networks:
  portfolio:
    driver: bridge
